name: 'Terraform'

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy_s3.yml'
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

#concurrency, we should only ever run this once across the entire repository
concurrency:
  group: deploys3
  cancel-in-progress: true

jobs:
  terraform-plan:
    name: 'Deploy S3'
    runs-on: ubuntu-latest
    environment: deploys3

    # Use the Bash shell regardless of the GitHub Actions runner's OS
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Configure AWS CLI (required for S3 backend)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'

      # Build nextjs frontend
      - name: Build NextJS frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      # Deploy frontend to s3 bucket using AWS CLI
      - name: Deploy to S3
        run: |
          aws s3 sync frontend/ s3://wombat-warden-s3-static-website/ --delete
